version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 300
exclude_patterns:
- "cypress/"
- "**/node_modules/"
- "temp/"
- "test/"